enum ScannerFileSource { CAMERA, GALLERY, PDF }
enum ScannerConfigsAndroid {
  ANDROID_NEXT_BUTTON_TITLE,
  ANDROID_SAVE_BUTTON_TITLE,
  ANDROID_ROTATE_LEFT_TITLE,
  ANDROID_ROTATE_RIGHT_TITLE,
  ANDROID_ORIGINAL_TITLE,
  ANDROID_BMW_TITLE
}
